server:
  port: 8080
  servlet:
    context-path: /LuxMedTask


spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/luxmed
    username: admin
    password: 1234
  jpa:
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect