git:
  static:
    val1: 6.0
    val2: 2.0
  client:
    api:
      url: https://api.github.com

server:
  port: 8080
  servlet:
    context-path: /git-client


spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb;
    driverClassName: org.h2.Driver
    username: sa
    password:
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    hibernate:
      ddl-auto: update

